services:
  - type: web
    name: neet-pg-checker
    env: node
    plan: starter
    runtime: node
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://neet-pg-checker.onrender.com
    # Explicitly exclude ALL Python-related files and directories
    excludePaths:
      - scripts/
      - *.py
      - *.pyc
      - __pycache__/
      - requirements.txt
      - setup.py
      - pyproject.toml
      - .DS_Store
      - .claude/
      - .playwright-mcp/
      - data/
      - *.pdf

databases:
  - name: neet-pg-checker-db
    plan: starter
    databaseName: neetpg
    user: neet_pg_user
