services:
  - type: web
    name: neet-pg-checker
    env: node
    plan: starter
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://neet-pg-checker.onrender.com

databases:
  - name: neet-pg-checker-db
    plan: starter
    databaseName: neetpg
    user: neet_pg_user
