services:
  - type: web
    name: neet-pg-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: neet-pg-db
          property: connectionString
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /health

databases:
  - name: neet-pg-db
    plan: free
    databaseName: neetpg
    user: neetpguser